name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Install dependencies
        run: yarn --immutable
      - name: Run Eslint
        run: yarn run lint --fix=false
      - name: Run Prettier
        run: yarn run format --write=false --check

  building:
    name: Building
    runs-on: ubuntu-latest
    needs: linting
    if: github.event_name != 'push' || !contains(github.ref, '/heads/master')
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup cache
        uses: actions/cache@v3
        with:
          path: .nuxt
          key: nuxt-cache
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Install dependencies
        run: yarn --immutable
      - name: Building
        run: yarn run generate